content_dir: results/nerf/LEGO/0
style_image: data/styles/3.jpg
vgg: data/pretrained/adain/vgg_normalised.pth
decoder: data/pretrained/adain/decoder.pth
content_size: 800
style_size: 800
crop: False
save_ext: .jpg
output: output
preserve_color: False # If specified, preserve color of the content image
alpha: 1.0 # content [0 ------> 1] style

