# content_image: results/nerf/LEGO/raw/001.png
# content_image: data/nerf_llff_data/trex/images/DJI_20200223_163553_010.jpg
# content_image: data/golden_gate.jpg
content_image: data/nerf_llff_data/orchids/images/IMG_4471.JPG
content_image: results/colmap/LLFF_FLOWER_PAMAD5_17/0/001.png 
# content_image: results/001_s_17.jpg
# content_image: results/001_s_17_s_17.jpg
# content_image: results/001_s_17_s_17_s_17.jpg
# content_image: results/001_s_17_s_17_s_17_s_17.jpg
style_image: data/styles/17.jpg
save_ext: .jpg
out_dir: results/gayts
height: 800

init_method: content
vgg_ckpt_path: data/pretrained/adain/vgg_normalised.pth
optimizer: lbfgs # [lbfgs | adam]
iterations: 3000 # [ 1000 | 3000] correspond to optimizer
saving_freq: -1 # -1:only save final image
lr_st: 1
lr: 10
content_weight: 100_000
style_weight: 1_000
tv_weight: 1

features: 
  - relu1_1
  - relu2_1
  - relu3_1
  - relu4_1
  - conv4_2
  - relu5_1
content_feature_index: 4
style_features_indices: 
  - 0
  - 1
  - 2
  - 3
  - 5