# [original | PAMA_1.5_color | PAMA_1.5_content | PAMA_without_color]
checkpoints: data/pretrained/pama/original 
content: data/lego/train/r_1.png # content image  or content dir if run_folder is True
style: data/styles/8.jpg # style image or style dir if run_folder is True

training: False
pretrained: True
requires_grad: False
