num_gpus: 1             # number of gpus
use_wandb: False        # use wandb or tensorboard
use_exposure: False               # whether to train in HDR-NeRF setting
distortion_loss_w: 0.0            # weight of distortion loss (see losses.py), 0 to disable (default), to enable, a good value is 1e-3 for real scene and 1e-2 for synthetic scene
optimize_ext: False               # whether to optimize extrinsics
random_bg: False                  # whether to train with random bg color (real scene only) to avoid objects with black color to be predicted as transparent

split: train                      # [train | trainval| trainvaltest] 
test_split: test

L: 16 # 多尺度特征层数。原始值: 16 
F: 2  # 每层特征维度。原始值: 2 
log2_T: 19 # 哈希表大小。原始值: 19 
N_min: 16 #　最低分辨率。原始值: 16 最高分辨率为2048
use_l1_loss: False
use_depth_loss: True
use_mod_ngp: False
weight_path: null
fix_encoder: False

eval_lpips: False                 # evaluate lpips metric (consumes more VRAM)
val_only: False                   # run only validation (need to provide ckpt_path)
no_save_test: False               # whether to save test image and video
fps: 5 # result video fps

vgg_pretrained: data/pretrained/adain/vgg_normalised.pth
decoder_pretrained: data/pretrained/adain/decoder.pth
save_ext: .png

# pama
# [original | PAMA_1.5_color | PAMA_1.5_content | PAMA_without_color]
checkpoints: data/pretrained/pama/original
training: False # control PAMANet forward path
pretrained: True
requires_grad: False

# ccpl
testing_mode: art # Artistic or Photo-realistic                    
vgg: data/pretrained/ccpl/vgg_normalised.pth
ccpl_decoder: data/pretrained/ccpl/decoder_iter_160000.pth.tar # decoder to load
SCT: data/pretrained/ccpl/sct_iter_160000.pth.tar # SCT module to load
preserve_color: False # If specified, preserve color of the content image')
# adain & ccpl
content_size: # h, w
  - 600
  - 800
style_size:
  - 600
  - 800
crop: False # do center crop to create squared image
alpha: 1.0 # more content [0 ------> 1] more style

# gayts
num_steps: 500
height: 600
init_method: content
vgg_ckpt_path: data/pretrained/adain/vgg_normalised.pth #FIXME repeat
optimizer: lbfgs # [lbfgs | adam]
iterations: 1000 # [ 1000 | 3000] correspond to optimizer
saving_freq: -1 # -1:only save final image

lr_st: 0.01
content_weight: 10
style_weight: 1
tv_weight: 0.001

features: 
  - relu1_1
  - relu2_1
  - relu3_1
  - relu4_1
  - conv4_2
  - relu5_1
content_feature_index: 4
style_features_indices: 
  - 0
  - 1
  - 2
  - 3
  - 5