#-------------------------------data & model----------------------------------

root_dir: data/nerf_llff_data/flower # root directory of dataset
exp_name: LLFF_FLOWER_ST_pama_73     # experiment name
ckpt_path: null
desc: Use NNST with depth loss and fix encoder
# ckpt_path: ckpts/colmap/LLFF_FLOWER_ST_NNST_8/epoch=7_slim.ckpt  # show_gui
weight_path: null
dataset_name: colmap              # [nerf | nsvf | colmap | nerfpp | rtmv] 
split: train                      # [train | trainval| trainvaltest] 
downsample: 0.1985                   # downsample factor (<=1.0) for the images wxh=800x600
# downsample: 0.126984                   # downsample factor (<=1.0) for the images 512
scale: 1.0                        # scene scale (whole scene must lie in [-scale, scale]^3

#-------------------------------basic----------------------------------------

L: 16 # 多尺度特征层数。原始值: 16 
F: 2  # 每层特征维度。原始值: 2 
log2_T: 19 # 哈希表大小。原始值: 19 
N_min: 16 #　最低分辨率。原始值: 16 
use_l1_loss: False
use_depth_loss: True
use_mod_ngp: False
fix_encoder: True

#-------------------------------training-------------------------------------

batch_size: 16384                  # number of rays in a batch
ray_sampling_strategy: same_image # [all_images | same_image] sample pixels in one image or all images
num_epochs: 8                     # number of training epochs
lr: 1.e-2                         # learning rate

#-------------------------------style transfer-------------------------------

style_transfer_method: nnst # [gayts(too slow) | adain | pama | ccpl]
style_image: data/styles/73.jpg
use_guided_filter: 0 # 0: disable, 1: guided_filter, 2:bilateral_filter
