exp_name: LEGO_PAMA               # experiment name
root_dir: data/lego               # root directory of dataset
ckpt_path: null
dataset_name: nerf                # [nerf | nsvf | colmap | nerfpp | rtmv] 
split: train                      # [train | trainval| trainvaltest] 
downsample: 1.0                   # downsample factor (<=1.0) for the images
scale: 0.5                        # scene scale (whole scene must lie in 
batch_size: 8192                  # number of rays in a batch
ray_sampling_strategy: all_images # [all_images | same_image] sample pixels in one image or all images
num_epochs: 5                     # number of training epochs
lr: 1.e-2                         # learning rate              
weight_path: null
fps: 10 # result video fps
use_depth_loss: True
# use_guided_filter: 1
#-------------------------------style transfer-------------------------------

style_transfer_method: pama # [gayts(too slow) | adain | pama | ccpl]
style_image: data/styles/73.jpg

content_size: # h, w
  - 800
  - 800
style_size:
  - 800
  - 800